server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: queueTest
  messages:
    basename: validations
  application:
    name: micro-cuentaMovimiento
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cuenta_movimiento_db
    username: root
    password: sasa
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
